version: '3.1'
services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - /opt/docker/ucw/volumes/pg-data-ucw:/var/lib/postgresql/data
    # networks:
    #   database:
    #     aliases:
    #       - db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres 
      POSTGRES_DB: ucw
    restart: unless-stopped
